name: Validate Plugin Registry PR

on:
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Community Repo
        uses: actions/checkout@v4

      - name: Setup Babashka
        uses: babashka/setup-babashka@v2
        with:
          version: '1.3.190'
      - name: Run Registry Validator
        run: bb aggregate.clj
